// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Entities;

public partial class AllCurrencies
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public string CountryCode { get; set; }
}