// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Entities;

public partial class ConversionRates
{
    public int Id { get; set; }

    public int FromCurrencyId { get; set; }

    public int ToCurrencyId { get; set; }

    public decimal Rate { get; set; }

    public virtual Currencies FromCurrency { get; set; }

    public virtual Currencies ToCurrency { get; set; }
}