// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Entities;

public partial class Currencies
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string CountryCode { get; set; }

    public string Symbol { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ConversionRates> ConversionRatesFromCurrency { get; set; } = new List<ConversionRates>();

    public virtual ICollection<ConversionRates> ConversionRatesToCurrency { get; set; } = new List<ConversionRates>();
}