// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Server.Entities;

public partial class CurrencyExchangeDbContext : DbContext
{
    public CurrencyExchangeDbContext(DbContextOptions<CurrencyExchangeDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ConversionRates> ConversionRates { get; set; }

    public virtual DbSet<Currencies> Currencies { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ConversionRates>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Conversi__3214EC071663788E");

            entity.HasIndex(e => new { e.FromCurrencyId, e.ToCurrencyId }, "UQ_Conversion").IsUnique();

            entity.Property(e => e.Rate).HasColumnType("decimal(18, 6)");

            entity.HasOne(d => d.FromCurrency).WithMany(p => p.ConversionRatesFromCurrency)
                .HasForeignKey(d => d.FromCurrencyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Conversion_From");

            entity.HasOne(d => d.ToCurrency).WithMany(p => p.ConversionRatesToCurrency)
                .HasForeignKey(d => d.ToCurrencyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Conversion_To");
        });

        modelBuilder.Entity<Currencies>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Currenci__3214EC078CF67135");

            entity.HasIndex(e => e.Code, "UQ__Currenci__A25C5AA7F7DD72B6").IsUnique();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC07858FA96A");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105345B1E5078").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}